### ISSUE TITLE
Migration to new KafkaChannel does take into account authentication defaults from old implementation

### ISSUE THREAD

**Issue by mgencur** [knative-sandbox/eventing-kafka-broker#2213] opened 2022-05-23 11:27 UTC
**Describe the bug**
The previous implementation of the channel did not require `protocol` and `sasl.mechanism` to be present in the Secret that was used for authentication.
The `protocol` settings is not required otherwise the Broker will fail with this error:
```
reason: 'error getting cluster admin config: protocol required (key: protocol)
      supported protocols: [PLAINTEXT SASL_PLAINTEXT SSL SASL_SSL]'
```
The sasl.mechanism now defaults to PLAIN as implemented in https://github.com/knative-sandbox/eventing-kafka-broker/issues/2117 but if the previous implementation was using some other mechanism, the new default (PLAIN) will not work with the existing Kafka cluster. This effectively breaks the existing deployments and the KafkaChannel stops working during the upgrade.

 **Expected behavior**
The protocol and sasl.mechanism is properly migrated when migrating from old to new channel implementation.

 **To Reproduce**
Assuming a Strimzi-installed Kafka in kafka namespace with:
```
       - name: sasl
         port: 9094
         type: internal
         tls: true
         authentication:
           type: scram-sha-512
```
and a KafkaUser my-sasl-user user.

* In a knative-eventing namespace, create the secret that will be used by KnativeKafka.
```
STRIMZI_CRT=$(oc -n kafka get secret my-cluster-cluster-ca-cert --template='{{index .data "ca.crt"}}' | base64 --decode )
SASL_PASSWD=$(oc -n kafka get secret my-sasl-user --template='{{index .data "password"}}' | base64 --decode )
oc create secret --namespace knative-eventing generic my-sasl-secret \
      --from-literal=ca.crt="$STRIMZI_CRT" \
      --from-literal=password="$SASL_PASSWD" \
      --from-literal=saslType="SCRAM-SHA-512" \
      --from-literal=user="my-sasl-user"
```
The secret above works fine with the previous implementation of the Channel.

* Now install the previous version of KnativeEventing and KnativeKafka with the following configs:
kafka-channel-config:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: kafka-channel-config
  namespace: knative-eventing
data:
  auth.secret.ref.name: my-sasl-secret
  auth.secret.ref.namespace: knative-eventing
  bootstrap.servers: 'my-cluster-kafka-bootstrap.kafka:9094'
```
config-br-default-channel:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: config-br-default-channel
  namespace: knative-eventing
data:
  channel-template-spec: |-
    apiVersion: messaging.knative.dev/v1beta1
    kind: KafkaChannel
    spec:
      numPartitions: 6
      replicationFactor: 3
      delivery:
        retry: 12
        backoffPolicy: exponential
        backoffDelay: PT1S
```
config-br-defaults:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: config-br-defaults
  namespace: knative-eventing
data:
  default-br-config: |
    clusterDefault:
      apiVersion: v1
      brokerClass: MTChannelBasedBroker
      delivery:
        backoffDelay: PT0.2S
        backoffPolicy: exponential
        retry: 10
      kind: ConfigMap
      name: config-br-default-channel
      namespace: knative-eventing
```
* Create a channel like this:
```
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: my-broker
  namespace: my-namespace
```
* Upgrade Eventing to the latest version which uses the new implementation.
* The channel ends up with error like this:
```
apiVersion: messaging.knative.dev/v1beta1
kind: KafkaChannel
metadata:
  annotations:
    eventing.knative.dev/scope: cluster
  creationTimestamp: "2022-05-23T08:47:23Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2022-05-23T08:57:39Z"
  finalizers:
  - kafkachannels.messaging.knative.dev
  generation: 2
  labels:
    eventing.knative.dev/broker: my-broker
    eventing.knative.dev/brokerEverything: "true"
  name: my-broker-kne-trigger
  namespace: serverless-tests
  ownerReferences:
  - apiVersion: eventing.knative.dev/v1
    blockOwnerDeletion: true
    controller: true
    kind: Broker
    name: my-broker
    uid: ef34b9f7-acc7-44bd-affb-31e42d5fc2c5
  resourceVersion: "125460"
  uid: 966c5534-2fb1-4e6b-9279-8f0fc402dfad
spec:
  delivery:
    backoffDelay: PT1S
    backoffPolicy: exponential
    retry: 12
  numPartitions: 6
  replicationFactor: 3
status:
  conditions:
  - lastTransitionTime: "2022-05-23T08:47:23Z"
    status: Unknown
    type: Addressable
  - lastTransitionTime: "2022-05-23T08:47:23Z"
    status: Unknown
    type: ConfigMapUpdated
  - lastTransitionTime: "2022-05-23T08:47:23Z"
    status: "True"
    type: ConfigParsed
  - lastTransitionTime: "2022-05-23T08:47:23Z"
    status: "True"
    type: DataPlaneAvailable
  - lastTransitionTime: "2022-05-23T08:47:23Z"
    status: Unknown
    type: ProbeSucceeded
  - lastTransitionTime: "2022-05-23T08:47:23Z"
    message: 'error getting cluster admin sarama config: protocol required (key: protocol)
      supported protocols: [PLAINTEXT SASL_PLAINTEXT SSL SASL_SSL]'
    reason: 'Failed to create topic: knative-messaging-kafka.serverless-tests.my-broker-kne-trigger'
    status: "False"
    type: Ready
  - lastTransitionTime: "2022-05-23T08:47:23Z"
    message: 'error getting cluster admin sarama config: protocol required (key: protocol)
      supported protocols: [PLAINTEXT SASL_PLAINTEXT SSL SASL_SSL]'
    reason: 'Failed to create topic: knative-messaging-kafka.serverless-tests.my-broker-kne-trigger'
    status: "False"
    type: TopicReady
  observedGeneration: 1
```

Note: If the secret was created like below the new implementation works as expected after upgrade:
```
oc create secret --namespace knative-eventing generic my-sasl-secret \
      --from-literal=ca.crt="$STRIMZI_CRT" \
      --from-literal=password="$SASL_PASSWD" \
      --from-literal=saslType="SCRAM-SHA-512" \
      --from-literal=user="my-sasl-user" \
      --from-literal=protocol="SASL_SSL" \  #This is added.
      --from-literal=sasl.mechanism="SCRAM-SHA-512" # This is added.
```

 **Knative release version**
1.2.3

**Comment by aliok** [comment] 2022-05-24 08:39
@pierDipi @matzew @mgencur 

The issue is that we use a different key in the secret now.

Old channel impl looks for `saslType` and the new one looks for `protocol`.

I don't want to touch user secrets during migration (sounds bad, but @mgencur to confirm) thus, I will make the code read old key in case the new key is missing.

**Comment by mgencur** [comment] 2022-05-24 08:56
It would be `saslType` in the old impl. vs. `sasl.mechanism` in the new one, right? I guess it's alright to read saslType if it is present. But not sure what to do about protocol. It needs to be determined from the old configuration somehow (not sure where it's stored)

**Comment by pierDipi** [comment] 2022-05-24 08:56
sounds good!

**Comment by aliok** [comment] 2022-05-24 08:58
> It would be saslType in the old impl. vs. sasl.mechanism in the new one, right?

Good point. I was mixing things.

**Comment by pierDipi** [comment] 2022-05-24 09:19
yes, we can but I'd recommend deprecating the old format and using the new one for consistency.

**Comment by aliok** [comment] 2022-05-24 09:53
> It needs to be determined from the old configuration somehow (not sure where it's stored)

Old logic is messy. There are multiple places with overriding mechanisims to determine the protocol... There's also backwards compatibility logic for configmap format for pre-distributed-channel-era.

> yes, we can but I'd recommend deprecating the old format and using the new one for consistency.

+1 on this, but we cannot do it right now...

I think the best is to have some logic (or even calling the old code in eventing-kafka) to build the auth config if `protocol` is missing. However, instead of carrying this over in channel code itself, I would like to do this in the migration code. However, that means I will touch the secret.

- Touch the secret and set protocol if it is missing
- Do it once in the migration code
- Do not have any fallback/legacy logic in the channel code

If we don't touch the secret, we will have the same problem: we will need to tell users to update their secret manually OR we carry the fallback logic forever.

**Comment by pierDipi** [comment] 2022-05-24 14:38
Another option is to create/update a new secret (that uses the new format) in the system namespace based on the user-referenced secret (that is in the old format) and we use the new secret internally

In the reconcile we will have something like this:
```golang
oldSecret := getUserSecret()
newSecret := reconcileNewSecret(oldSecret)
// use `n` for contract, etc
```

**Comment by pierDipi** [comment] 2022-05-24 14:46
The problem with touching external secrets is that they might be reconciled by a different system and so we will endup either fighting (if done in the reconciler) or in a broken state (if done in the migration job)

**Comment by aliok** [comment] 2022-05-24 14:53
https://github.com/knative-sandbox/eventing-kafka-broker/pull/2216

have a quick look? this touches the secret

**Comment by aliok** [comment] 2022-05-24 14:55
```
Another option is to create/update a new secret (that uses the new format) in the system namespace based on the user-referenced secret (that is in the old format) and we use the new secret internally
```

The issue is we will carry this legacy logic until we ask manual interaction.


Well, anyway, I did the hard part in https://github.com/knative-sandbox/eventing-kafka-broker/pull/2216, which is determining what protocol the consolidated channel was using.

**Comment by pierDipi** [comment] 2022-05-25 07:17
I don't see why option 3 shouldn't work, so I would investigate that one and we keep reading whatever user secret is provided + we need to determine the "protocol".

next, we will implement the new format for the channel. 
For now, we can focus on keeping the compatibility with the old format.

**Comment by pierDipi** [comment] 2022-05-25 07:20
> I am not 100% sure if we can delete config-kafka for a while. Because, in the legacy channel, it is also used to build the auth config. Not everything is in the secret and CR.

we can keep it around if we need it for this migration until we deprecate and remove the old format

**Comment by matzew** [comment] 2022-05-25 07:23
I agree on trying the suggested `option 3`

**Comment by pierDipi** [comment] 2022-05-25 07:44
For option 3.

Based on the content of the old format channel secret:
- Determine MultiSecretReference.protocol 
- create the MultiSecretReference.references array, it will contain only one element with: 
  - [the secret reference (name, namespace, etc)](https://github.com/knative-sandbox/eventing-kafka-broker/blob/4176f0b593872ed1dee0f72f30787cfa34fa308f/proto/contract.proto#L208)
  - [create the keyFieldReferences array](https://github.com/knative-sandbox/eventing-kafka-broker/blob/4176f0b593872ed1dee0f72f30787cfa34fa308f/proto/contract.proto#L211), each with:
    - [a key](https://github.com/knative-sandbox/eventing-kafka-broker/blob/4176f0b593872ed1dee0f72f30787cfa34fa308f/proto/contract.proto#L216)
    - [a secret field type (what that key represents TLS CA, TLS key, etc)](https://github.com/knative-sandbox/eventing-kafka-broker/blob/4176f0b593872ed1dee0f72f30787cfa34fa308f/proto/contract.proto#L197-L204)

**Comment by aliok** [comment] 2022-05-25 08:41
> sarama configs shouldn't be strictly needed in our case since we don't use sarama consumers and producers
Yeah, but some of the TLS/SASL config was specified there directly. That's why I told we might need them too.

**Comment by pierDipi** [comment] 2022-05-30 07:34
with https://github.com/knative-sandbox/eventing-kafka-broker/pull/2224 using this secret [1] will work.

[1]
```
  kubectl create secret --namespace "${SYSTEM_NAMESPACE}" generic strimzi-sasl-secret-legacy \
    --from-literal=ca.crt="$STRIMZI_CRT" \
    --from-literal=password="$SASL_PASSWD" \
    --from-literal=user="my-sasl-user" \
    --from-literal=saslType="SCRAM-SHA-512" \
    --dry-run=client -o yaml | kubectl apply -n "${SYSTEM_NAMESPACE}" -f -
```

**Comment by aliok** [comment] 2022-05-30 07:50
/close

Fixed by https://github.com/knative-sandbox/eventing-kafka-broker/pull/2224

**Closed by aliok** 2022-05-30 07:50 UTC
Labels: kind/bug, triage/accepted, area/channel
