### ISSUE TITLE
cosumers conflict between kafkasource and kafka-source-dispatcher

### ISSUE THREAD

**Issue by ninoamine** [knative-sandbox/eventing-kafka-broker#3229] opened 2023-07-25 12:23 UTC
**Describe the bug**
When I create kafkasource that consume messages from a topic with one partition, it creates a consumer groupe with 3 members one for the kafkasource and two for the kafka-source-dispatcher, so when I produce a message in my topic it is consumed by one of the consumer of kafka-source-dispatcher so it is kind of lost.

 **Expected behavior**
Normalement it should be one consumer of the kafkasource pod

**knative-eventing version: 1.3.2**

 **Additional context**
I don't understand why the dispatcher add those consumer it brokes the workflow

**Comment by pierDipi** [comment] 2023-07-25 12:36
@ninoamine please provide steps to reproduce on a more recent version of Knative, 1.3.2 is quite old and the community doesn't support it anymore

**Comment by ninoamine** [comment] 2023-07-25 12:39
we are kind of stuck un this version because of some infrastrucutre dependencies, but can I at least know what is the use of the kafka-source-dispatcher and why does it need to create consumer beside the consume of the kafkasource pord ?

**Comment by pierDipi** [comment] 2023-07-25 12:41
without such jobs you will get competing components trying to handle a single KafkaSource

**Comment by ninoamine** [comment] 2023-07-25 12:43
we used the operator to install knative eventing, the post install is not managed by default in it ?

**Comment by pierDipi** [comment] 2023-07-25 12:45
The operator would work if you install only KafkaSource but probably you are installing Knative Broker with class Kafka or KafkaChannel as well, in that case, the Knative Kafka components should not be managed by the operator (aka you should disable operator support for Kafka source)

**Comment by pierDipi** [comment] 2023-07-25 12:46
Can you perhaps share more about your configurations, what the KnativeEventing CR look like? what's your cluster state currently (ie list pods in knative-eventing and user's namespaces where KafkaSource are, etc)?

**Comment by ninoamine** [comment] 2023-07-25 12:53
of course:
this is the knativeeventing cr manifest
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  config:
    logging:
      loglevel.controller: debug
      loglevel.webhook: debug
      zap-logger-config: "{\n \"level\": \"debug\",\n \"development\": false,\n \"outputPaths\":
        [\"stdout\"],\n \"errorOutputPaths\": [\"stderr\"],\n \"encoding\": \"json\",\n
        \"encoderConfig\": {\n   \"timeKey\": \"ts\",\n   \"levelKey\": \"level\",\n
        \  \"nameKey\": \"logger\",\n   \"callerKey\": \"caller\",\n   \"messageKey\":
        \"msg\",\n   \"stacktraceKey\": \"stacktrace\",\n   \"lineEnding\": \"\",\n
        \  \"levelEncoder\": \"\",\n   \"timeEncoder\": \"iso8601\",\n   \"durationEncoder\":
        \"\",\n   \"callerEncoder\": \"\"\n   }  \n}\n"
  high-availability:
    replicas: 1
  source:
    kafka:
      enabled: true

we also installed :
apache kafka controller https://github.com/knative-sandbox/eventing-kafka-broker/releases/download/knative-v1.3.2/eventing-kafka-controller.yaml

kafka channel data plane https://github.com/knative-sandbox/eventing-kafka-broker/releases/download/knative-v1.3.2/eventing-kafka-channel.yaml

kadka source data plane https://github.com/knative-sandbox/eventing-kafka-broker/releases/download/knative-v1.3.2/eventing-kafka-source.yaml

apache kafka broker https://github.com/knative-sandbox/eventing-kafka-broker/releases/download/knative-v1.3.2/eventing-kafka-broker.yaml

Apache Kafka Sink https://github.com/knative-sandbox/eventing-kafka-broker/releases/download/knative-v1.3.2/eventing-kafka-sink.yaml

and this the element that we have in knative-eventing ns
NAME                       READY   UP-TO-DATE   AVAILABLE   AGE
eventing-controller        1/1     1            1           14d
eventing-webhook           1/1     1            1           14d
imc-controller             1/1     1            1           14d
imc-dispatcher             1/1     1            1           14d
kafka-broker-dispatcher    2/2     2            2           14d
kafka-broker-receiver      1/1     1            1           14d
kafka-channel-dispatcher   1/1     1            1           14d
kafka-channel-receiver     1/1     1            1           14d
kafka-controller           1/1     1            1           14d
kafka-controller-manager   1/1     1            1           14d
kafka-sink-receiver        1/1     1            1           14d
kafka-source-dispatcher    0/0     0            0           14d
kafka-webhook-eventing     1/1     1            1           14d
mt-broker-controller       1/1     1            1           14d
mt-broker-filter           1/1     1            1           14d
mt-broker-ingress          1/1     1            1           14d
pingsource-mt-adapter      0/0     0            0           14d
sugar-controller           1/1     1            1           14d

**Comment by ninoamine** [comment] 2023-07-25 12:55
maybe as you said we have some comflict with resources created by the operator and the one that we installed by manifest

**Comment by pierDipi** [comment] 2023-07-25 13:13
Yes, that's the reason, you should disable kafka source in the KnativeEventing CR and re-apply eventing-kafka-broker repositories YAMLs (including the post-install artifact)

**Comment by pierDipi** [comment] 2023-07-26 14:10
Closing this as comments were addressed

**Closed by pierDipi** 2023-07-26 14:10 UTC
Labels: kind/bug, triage/needs-user-input
